baseURL = 'https://blog.134256.xyz/'
languageCode = 'zh-cn'
title = "Byron's Blog"
theme = ['hugo-chart', 'hugo-social-metadata', 'hugo-theme-stack']


[Params]
description = "Is what define us?"
rssFullContent = true
mainSections = ["posts"]
twitterUsername = "@ElectricityRed"

[[Params.widgets.homepage]]
type = "search"


[[Params.widgets.homepage]]
type = "categories"

[Params.widgets.homepage.params]
limit = 10

[[Params.widgets.page]]
type = "toc"

[Params.article]
toc = true
readingTime = true
math = true

[Params.Sidebar]
subtitle = "Is what define us?"

[Params.Sidebar.avatar]
enabled = false
local = false
src = "https://avatars.githubusercontent.com/u/75127571"

[Params.Footer]
customText = 'Powered by RedElectricity with Love❤️'

[menu]
[[menu.main]]
    name = "Articles"
    url = "/"
    weight = 10
    identifier = "home"
[[menu.main]]
    name = "Categories"
    url = "/categories"
    weight = 10
    identifier = "categories"

[[menu.social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/RedElectricity"
[menu.social.params]
icon = "brand-github"

[[menu.social]]
identifier = "twitter"
name = "Twitter"
url = "https://twitter.com/ElectricityRed"
[menu.social.params]
icon = "brand-twitter"

[[menu.social]]
identifier = "weibo"
name = "Weibo"
url = "https://www.weibo.com/u/7891027455"
[menu.social.params]
icon = "brand-weibo"

[[menu.social]]
identifier = "email"
name = "Email"
url = "redelectricity@outlook.com"
[menu.social.params]
icon = "brand-mail"
