baseURL = 'https://blog.134256.xyz/'
languageCode = 'zh-cn'
title = "Byron's Blog"
theme = ['hugo-admonitions', 'hugo-chart', 'hugo-social-metadata', 'hugo-theme-stack']

ignoreLogs = ['warning-goldmark-raw-html']

[Params]
description = "Let's rewrite the world."
rssFullContent = true
mainSections = ["posts"]
twitterUsername = "@ByronConra1780"

[[Params.widgets.homepage]]
type = "search"


[[Params.widgets.homepage]]
type = "categories"

[Params.widgets.homepage.params]
limit = 10

[[Params.widgets.page]]
type = "toc"

[Params.article]
toc = true
readingTime = true
math = true

[Params.Sidebar]
subtitle = "Let's rewrite the world."

[Params.Sidebar.avatar]
enabled = false
local = false
src = "https://avatars.githubusercontent.com/u/75127571"

[Params.opengraph.twitter]
site = 'ByronConra1780'
card = 'summary_large_image'

[Params.Footer]
customText = 'Powered by RedElectricity with Love❤️'

[menu]
[[menu.main]]
    name = "Articles"
    url = "/"
    weight = 10
    identifier = "home"
[[menu.main]]
    name = "Categories"
    url = "/categories"
    weight = 10
    identifier = "categories"

[[menu.social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/RedElectricity"
[menu.social.params]
icon = "brand-github"

[[menu.social]]
identifier = "twitter"
name = "Twitter"
url = "https://twitter.com/ByronConra1780"
[menu.social.params]
icon = "brand-twitter"

[[menu.social]]
identifier = "weibo"
name = "Weibo"
url = "https://www.weibo.com/u/7891027455"
[menu.social.params]
icon = "brand-weibo"

[[menu.social]]
identifier = "email"
name = "Email"
url = "redelectricity@outlook.com"
[menu.social.params]
icon = "brand-mail"

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)'], ['$', '$']]
      [markup.goldmark.extensions.extras]
        [markup.goldmark.extensions.extras.delete]
          enable = true
        [markup.goldmark.extensions.extras.insert]
          enable = true
        [markup.goldmark.extensions.extras.mark]
          enable = true
        [markup.goldmark.extensions.extras.subscript]
          enable = true
        [markup.goldmark.extensions.extras.superscript]
          enable = true